import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState } from 'react';

export default function Home() {
  const [email, setEmail] = useState({
    email: '',
    subcriptionResponse: '',
    error: false,
  });

  const handleSubmit = async () => {
    try {
      const signup = await fetch('/api/signup', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          email_address: email.email,
          status: 'subscribed',
        }),
      });
      const response = await signup.json();

      setEmail({
        email: '',
        subcriptionResponse: response.message,
        error: false,
      });
    } catch (error) {
      setEmail({ ...email, subcriptionResponse: error, error: true });
    }
  };

  return (
    <>
      <Head>
        <title>MailChimp NextJS Subcription</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <form
            onSubmit={(e) => {
              e.preventDefault();
              // Call the handleSubmit function
              handleSubmit();
            }}
            className={styles.form}
          >
            <div className={'inputContainer'}>
              <input
                type={'email'}
                placeholder={'Please enter your email address'}
                value={email.email}
                onChange={(e) => setEmail({ ...email, email: e.target.value })}
                required
                className={styles.input}
              />
            </div>

            <button type={'submit'} className={styles.button}>
              Notify me
            </button>
            <p style={{ color: email.error ? 'red' : 'green' }}>
              {email?.subcriptionResponse}
            </p>
          </form>
        </div>
      </main>
    </>
  );
}
